### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by ITTDublinComputerScienceSociety** [ITTDublinComputerScienceSociety/itt-comp-soc-website#1]
We need to create a "CONTRIBUTING.MD" to define what is the objective of this website, what needs to be improved first etc

you can use my example here:
https://github.com/ITTDublinComputerScienceSociety/MicrosoftCodingCompetition2016/blob/master/CONTRIBUTING.md

**Comment by dmateusp** [comment]
done here d4fea8aa52514925605736e00d07e70410bb75ad, to close
